/**
 * Ed25519 sign / verify wrapper — behavior tests.
 *
 * Pins the algorithm-pinning + verify-returns-bool-not-throw + base64
 * round-trip invariants from the AJS-55 design's §"Risk model" — in
 * particular the algorithm-confusion defense: even a valid signature
 * from a non-ed25519 key MUST be rejected.
 */

import { describe, expect, test } from "bun:test";
import { generateKeyPairSync } from "node:crypto";
import {
  base64ToBytes,
  bytesToBase64,
  generateEd25519KeyPair,
  signEd25519,
  verifyEd25519,
} from "../src/ed25519.ts";

describe("packages/host/tests/ed25519.test.ts — sign/verify/base64 contract", () => {
  /**
   * WHAT: A keypair generated by `generateEd25519KeyPair` can sign a
   *       byte string AND the signature verifies under the public key.
   * WHY: Round-trip pin. Without this, every reject test below could
   *      pass while the positive path is broken — a "verify always
   *      false" regression would still pass tampering tests.
   */
  test("happy path: generate → sign → verify (same keypair)", () => {
    const { privateKeyPem, publicKeyPem } = generateEd25519KeyPair();
    const bytes = new TextEncoder().encode("hello AJS-55");
    const sig = signEd25519(privateKeyPem, bytes);
    expect(sig.byteLength).toBe(64); // ed25519 signatures are 64 bytes
    expect(verifyEd25519(publicKeyPem, bytes, sig)).toBe(true);
  });

  /**
   * WHAT: A signature from keypair A does NOT verify under keypair B's
   *       public key.
   * WHY: The core security property. If verify accepted any signature
   *      regardless of which key produced it, every other check is
   *      decorative.
   */
  test("signature from key A does NOT verify under key B's public key", () => {
    const keypairA = generateEd25519KeyPair();
    const keypairB = generateEd25519KeyPair();
    const bytes = new TextEncoder().encode("AJS-55 peer record body");
    const sigByA = signEd25519(keypairA.privateKeyPem, bytes);
    expect(verifyEd25519(keypairB.publicKeyPem, bytes, sigByA)).toBe(false);
  });

  /**
   * WHAT: A signature over `bytesA` does NOT verify under `bytesB`
   *       even with the matching public key.
   * WHY: Pins that the signature is bound to the EXACT bytes, not
   *      just the key. A regression that accepted any signature from
   *      the right key (e.g. by mis-passing bytes to verify) would
   *      defeat the "tamper-evident" property of the signed records.
   */
  test("signature does NOT verify against tampered bytes", () => {
    const { privateKeyPem, publicKeyPem } = generateEd25519KeyPair();
    const original = new TextEncoder().encode("original AJS-55 payload");
    const tampered = new TextEncoder().encode("TAMPERED AJS-55 payload");
    const sig = signEd25519(privateKeyPem, original);
    expect(verifyEd25519(publicKeyPem, tampered, sig)).toBe(false);
  });

  /**
   * WHAT: Loading a PEM that's not ed25519 (e.g. an RSA private key)
   *       into `signEd25519` throws with a clear algorithm-mismatch
   *       error. `verifyEd25519` returns `false` for the same input
   *       (does not throw — verify uses fail-closed bool semantics).
   * WHY: Algorithm-confusion defense per AJS-55 §"Risk model". Sign
   *      is operator-action (throw is fine; loud failure surfaces the
   *      misconfig). Verify is request-path (must not throw — see
   *      next test). Pin both shapes.
   */
  test("non-ed25519 key (RSA PEM) → sign throws; verify returns false", () => {
    const { privateKey, publicKey } = generateKeyPairSync("rsa", { modulusLength: 2048 });
    const rsaPrivatePem = privateKey.export({ type: "pkcs8", format: "pem" }) as string;
    const rsaPublicPem = publicKey.export({ type: "spki", format: "pem" }) as string;
    const bytes = new TextEncoder().encode("hello");
    expect(() => signEd25519(rsaPrivatePem, bytes)).toThrow(/ed25519/);
    expect(verifyEd25519(rsaPublicPem, bytes, new Uint8Array(64))).toBe(false);
  });

  /**
   * WHAT: `verifyEd25519` returns `false` (not throws) on malformed
   *       PEM, malformed signature length, etc.
   * WHY: Verify is on the REQUEST PATH — every inbound peer-record
   *      or challenge-mint signature triggers a verify call. If the
   *      function threw on every garbage input, a malicious caller
   *      could DoS the gateway by submitting a stream of malformed
   *      signatures and forcing exception-handling overhead in the
   *      dispatcher. Returning `false` keeps the cost bounded.
   */
  test("verify returns false (not throws) on malformed PEM / signature", () => {
    const malformedPem = "-----BEGIN PUBLIC KEY-----\nGARBAGE\n-----END PUBLIC KEY-----\n";
    const bytes = new TextEncoder().encode("hello");
    const sig = new Uint8Array(64);
    expect(verifyEd25519(malformedPem, bytes, sig)).toBe(false);
    expect(verifyEd25519("not a PEM at all", bytes, sig)).toBe(false);
    // Wrong-length signature (32 bytes instead of 64):
    const { publicKeyPem } = generateEd25519KeyPair();
    expect(verifyEd25519(publicKeyPem, bytes, new Uint8Array(32))).toBe(false);
  });

  /**
   * WHAT: `bytesToBase64` round-trips through `base64ToBytes` to the
   *       original byte sequence.
   * WHY: Peer records carry signatures + pubkeys as base64 strings on
   *      the wire (JSON-friendly). A regression in either direction
   *      breaks the deserialization path. Pin the round-trip.
   */
  test("base64 round-trip preserves bytes", () => {
    const original = new Uint8Array([0, 1, 2, 3, 254, 255, 128, 64]);
    const encoded = bytesToBase64(original);
    const decoded = base64ToBytes(encoded);
    expect(decoded).toEqual(original);
  });

  /**
   * WHAT: `base64ToBytes` throws on input containing non-base64
   *       characters or wrong-length padding.
   * WHY: Node's `Buffer.from(str, 'base64')` is lenient — silently
   *      skips invalid chars. For cryptographic input we want loud
   *      failure on corruption rather than silently treating garbage
   *      as a short-but-valid byte sequence (which the verifier
   *      would then reject for the wrong reason — "signature
   *      invalid" instead of "signature was corrupted in transport").
   */
  test("base64ToBytes rejects malformed input", () => {
    expect(() => base64ToBytes("not!base64@all")).toThrow(/invalid base64/);
    expect(() => base64ToBytes("ABC")).toThrow(/invalid base64/); // length not multiple of 4
  });
});
