import { describe, expect, test } from "bun:test";
import type { MemoryRecord } from "@agents-js/memory";
import type { Storage, StoredRecord } from "../src/storage.ts";

/**
 * Shape tests for the Storage seam.
 *
 * These tests assert the SHAPE of the contract — they do not exercise a
 * real storage implementation. The bundled `SqliteStorage` provides the
 * reference impl; behavior conformance lives in its dedicated tests.
 *
 * Each test below uses a minimal object-literal mock that satisfies the
 * `Storage` interface. The point is to nail down the method signatures
 * and behaviors that any future Storage implementation MUST satisfy.
 */

function baseRecord(overrides: Partial<StoredRecord> = {}): StoredRecord {
  return {
    id: "mem_1",
    scope: { kind: "global" },
    type: "user",
    content: "hello",
    metadata: {},
    createdAtMs: 0,
    updatedAtMs: 0,
    revision: "1",
    creator: { kind: "agent", actorId: "a1" },
    idempotencyKey: undefined,
    ...overrides,
  };
}

describe("Storage — interface contract", () => {
  // Intent: any Storage impl must accept a record whose id was generated by
  // the storage layer itself. This documents that the caller (the provider)
  // is permitted to supply an id (it owns id generation in v1), but the
  // seam still supports an impl that defers id assignment to the backend.
  test("any Storage impl must support insertRecord with auto-generated id", async () => {
    const storage: Storage = {
      async insertRecord(record) {
        return { ...record, id: record.id || "auto_generated_1" };
      },
      async updateRecord() {
        throw new Error("not used in this test");
      },
      async getRecord() {
        return undefined;
      },
      async deleteRecord() {
        return false;
      },
      async findByIdempotency() {
        return undefined;
      },
      async listByScope() {
        return { records: [], cursor: null };
      },
      async close() {},
    };

    const inserted = await storage.insertRecord(baseRecord({ id: "" }));
    expect(inserted.id).toBe("auto_generated_1");
  });

  // Intent: the v1 provider owns id generation, so the seam MUST
  // round-trip a caller-supplied id verbatim. Test pins that contract.
  test("any Storage impl must support insertRecord with caller-supplied id", async () => {
    const storage: Storage = {
      async insertRecord(record) {
        return record;
      },
      async updateRecord() {
        throw new Error("not used in this test");
      },
      async getRecord() {
        return undefined;
      },
      async deleteRecord() {
        return false;
      },
      async findByIdempotency() {
        return undefined;
      },
      async listByScope() {
        return { records: [], cursor: null };
      },
      async close() {},
    };

    const inserted = await storage.insertRecord(baseRecord({ id: "mem_explicit_42" }));
    expect(inserted.id).toBe("mem_explicit_42");
  });

  // Intent: the seam exposes optimistic concurrency via `expectedRevision`.
  // When the stored record's revision does not match, the impl returns
  // `{ ok: false, current }` so the provider can lift it to a
  // MemoryRevisionConflictError without the seam knowing the error type.
  test("any Storage impl must support updateRecord with expectedRevision conflict detection", async () => {
    const storage: Storage = {
      async insertRecord(record) {
        return record;
      },
      async updateRecord(_id, _patch, expectedRevision) {
        if (expectedRevision !== undefined && expectedRevision !== "1") {
          return { ok: false, current: baseRecord({ revision: "1" }) };
        }
        return { ok: true, record: baseRecord({ revision: "2" }) };
      },
      async getRecord() {
        return undefined;
      },
      async deleteRecord() {
        return false;
      },
      async findByIdempotency() {
        return undefined;
      },
      async listByScope() {
        return { records: [], cursor: null };
      },
      async close() {},
    };

    const conflict = await storage.updateRecord("mem_1", { content: "x" }, "stale");
    expect(conflict.ok).toBe(false);
    if (!conflict.ok) {
      expect(conflict.current.revision).toBe("1");
    }

    const ok = await storage.updateRecord("mem_1", { content: "x" }, "1");
    expect(ok.ok).toBe(true);
  });

  // Intent: unknown id MUST resolve to `undefined`, never throw. Throwing
  // would force the provider into try/catch for every read, and the
  // seam has no semantic context to distinguish "missing" from "I/O failed".
  test("any Storage impl must support getRecord by id returning undefined for unknown id", async () => {
    const storage: Storage = {
      async insertRecord(record) {
        return record;
      },
      async updateRecord() {
        throw new Error("not used in this test");
      },
      async getRecord(id) {
        if (id === "known") return baseRecord({ id: "known" });
        return undefined;
      },
      async deleteRecord() {
        return false;
      },
      async findByIdempotency() {
        return undefined;
      },
      async listByScope() {
        return { records: [], cursor: null };
      },
      async close() {},
    };

    expect(await storage.getRecord("unknown")).toBeUndefined();
    const hit = await storage.getRecord("known");
    expect(hit?.id).toBe("known");
  });

  // Intent: deleteRecord returns a boolean so the provider can distinguish
  // "deleted N=1" from "id was not present". MemoryProvider.deleteMemory
  // is idempotent (returns void either way), but the seam preserves the
  // signal in case a future provider wants to expose it.
  test("any Storage impl must support deleteRecord by id returning a delete-result indicator", async () => {
    const storage: Storage = {
      async insertRecord(record) {
        return record;
      },
      async updateRecord() {
        throw new Error("not used in this test");
      },
      async getRecord() {
        return undefined;
      },
      async deleteRecord(id) {
        return id === "known";
      },
      async findByIdempotency() {
        return undefined;
      },
      async listByScope() {
        return { records: [], cursor: null };
      },
      async close() {},
    };

    expect(await storage.deleteRecord("known")).toBe(true);
    expect(await storage.deleteRecord("missing")).toBe(false);
  });

  // Intent: idempotency lookup is scoped by (creatorKind, creatorId, key)
  // — the SAME key from a different actor MUST NOT collide. This pins
  // the seam's scoping rule so the sqlite impl doesn't accidentally
  // index by `key` alone.
  test("any Storage impl must support findByIdempotency returning matching prior record or undefined", async () => {
    const prior = baseRecord({
      id: "mem_existing",
      creator: { kind: "agent", actorId: "a1" },
      idempotencyKey: "k1",
    });
    const storage: Storage = {
      async insertRecord(record) {
        return record;
      },
      async updateRecord() {
        throw new Error("not used in this test");
      },
      async getRecord() {
        return undefined;
      },
      async deleteRecord() {
        return false;
      },
      async findByIdempotency(creatorKind, creatorId, key) {
        if (creatorKind === "agent" && creatorId === "a1" && key === "k1") {
          return prior;
        }
        return undefined;
      },
      async listByScope() {
        return { records: [], cursor: null };
      },
      async close() {},
    };

    const hit = await storage.findByIdempotency("agent", "a1", "k1");
    expect(hit?.id).toBe("mem_existing");
    expect(await storage.findByIdempotency("agent", "other", "k1")).toBeUndefined();
    expect(await storage.findByIdempotency("agent", "a1", "k2")).toBeUndefined();
  });

  // Intent: close() is the resource-release hook (sqlite handle, file
  // descriptor, etc.). Callers — including the provider's own teardown
  // and the smoke example — MUST be able to call it twice without an
  // error, so the seam pins idempotency now.
  test("any Storage impl must support close() idempotent (calling twice is a no-op)", async () => {
    let closeCount = 0;
    const storage: Storage = {
      async insertRecord(record) {
        return record;
      },
      async updateRecord() {
        throw new Error("not used in this test");
      },
      async getRecord() {
        return undefined;
      },
      async deleteRecord() {
        return false;
      },
      async findByIdempotency() {
        return undefined;
      },
      async listByScope() {
        return { records: [], cursor: null };
      },
      async close() {
        closeCount += 1;
      },
    };

    await storage.close();
    await storage.close();
    expect(closeCount).toBe(2); // both calls succeed; the seam allows them
  });

  // Sanity: MemoryRecord and StoredRecord share the public shape. If
  // someone widens StoredRecord beyond what MemoryRecord requires, this
  // assertion still type-checks because StoredRecord extends MemoryRecord.
  test("StoredRecord is assignable to MemoryRecord (public shape preserved)", () => {
    const stored: StoredRecord = baseRecord();
    const asPublic: MemoryRecord = stored;
    expect(asPublic.id).toBe(stored.id);
  });
});
