/**
 * Generate `docs/public/capability-status.json` from the hand-authored
 * classification in `scripts/capability-status.json`, JOINED against
 * `docs/public/graph.json`.
 *
 * Usage:
 *   bun scripts/capability-status.ts --write   # regenerate the artifact
 *   bun scripts/capability-status.ts --check   # fail on drift (no writes)
 *
 * The generator NEVER infers a capability tier — tier authority belongs to the
 * capability-reconciliation effort and lives in `scripts/capability-status.json`.
 * Its only honesty checks are STRUCTURAL: every `tier` must be in the enum, and
 * every package referenced by a capability must exist in `graph.json` (a stale
 * or typo'd package ref fails the gate loudly). It enriches each referenced
 * package with `{name, dir, version}` from the graph and computes tier counts.
 *
 * The drift gate (`docs:capability-status:check`, run from `bun run check`)
 * compares everything EXCEPT the volatile `generated_at` / `source_commit`
 * fields, so committing the artifact does not churn on timestamps.
 */

import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const SOURCE = join(ROOT, "scripts/capability-status.json");
const GRAPH = join(ROOT, "docs/public/graph.json");
const OUT = join(ROOT, "docs/public/capability-status.json");

const TIERS = ["demonstrated", "undemonstrated", "over-claimed", "missing"] as const;
type Tier = (typeof TIERS)[number];

interface EvidenceEntry {
  kind: string;
  ref: string;
  note: string;
}
interface SourceCapability {
  title: string;
  tier: string;
  packages: string[];
  evidence: EvidenceEntry[];
  notes?: string;
}
interface SourceFile {
  capabilities: Record<string, SourceCapability>;
}
interface GraphPackage {
  name: string;
  dir: string;
  version: string;
}

function gitShortSha(): string {
  const r = spawnSync("git", ["rev-parse", "--short", "HEAD"], { cwd: ROOT, encoding: "utf-8" });
  return r.status === 0 ? r.stdout.trim() : "unknown";
}

function loadGraph(): Map<string, GraphPackage> {
  const raw = JSON.parse(readFileSync(GRAPH, "utf-8")) as unknown;
  const arr = (
    Array.isArray(raw) ? raw : ((raw as { packages?: unknown }).packages ?? [])
  ) as GraphPackage[];
  return new Map(arr.map((p) => [p.name, { name: p.name, dir: p.dir, version: p.version }]));
}

/** Build the generated artifact, validating structure + the graph join. Throws on any violation. */
function build(): Record<string, unknown> {
  const source = JSON.parse(readFileSync(SOURCE, "utf-8")) as SourceFile;
  const graph = loadGraph();
  const errors: string[] = [];

  const capabilities = Object.entries(source.capabilities).map(([id, cap]) => {
    if (!TIERS.includes(cap.tier as Tier)) {
      errors.push(
        `capability "${id}": invalid tier "${cap.tier}" (expected one of ${TIERS.join(", ")})`,
      );
    }
    const packages = cap.packages.map((name) => {
      const pkg = graph.get(name);
      if (!pkg) {
        errors.push(`capability "${id}": package "${name}" not found in graph.json`);
        return { name, dir: "", version: "" };
      }
      return pkg;
    });
    return {
      id,
      title: cap.title,
      tier: cap.tier,
      packages,
      evidence: cap.evidence,
      notes: cap.notes ?? "",
    };
  });

  if (errors.length > 0) {
    throw new Error(
      `capability-status: ${errors.length} validation error(s):\n  - ${errors.join("\n  - ")}`,
    );
  }

  const tierCounts = Object.fromEntries(
    TIERS.map((t) => [t, capabilities.filter((c) => c.tier === t).length]),
  );

  return {
    _comment:
      "GENERATED by scripts/capability-status.ts from scripts/capability-status.json + docs/public/graph.json. Do not edit by hand.",
    generated_at: new Date().toISOString(),
    source_commit: gitShortSha(),
    tier_counts: tierCounts,
    capabilities,
  };
}

/** Strip volatile fields so committing the artifact does not churn on timestamps/SHA. */
function stable(obj: Record<string, unknown>): string {
  const { generated_at: _g, source_commit: _s, ...rest } = obj;
  return JSON.stringify(rest, null, 2);
}

function main(): void {
  const checkMode = process.argv.includes("--check");
  const writeMode = process.argv.includes("--write");
  if (checkMode === writeMode) {
    console.error("Usage: bun scripts/capability-status.ts (--check | --write)");
    process.exit(2);
  }

  const generated = build();

  if (writeMode) {
    writeFileSync(OUT, `${JSON.stringify(generated, null, 2)}\n`, "utf-8");
    const counts = generated.tier_counts as Record<string, number>;
    console.log(
      `✓ capability-status: wrote docs/public/capability-status.json (${(generated.capabilities as unknown[]).length} capabilities: ${Object.entries(
        counts,
      )
        .map(([t, n]) => `${n} ${t}`)
        .join(", ")})`,
    );
    return;
  }

  let current: Record<string, unknown>;
  try {
    current = JSON.parse(readFileSync(OUT, "utf-8")) as Record<string, unknown>;
  } catch {
    console.error(
      "✗ capability-status: docs/public/capability-status.json missing or unparseable; run bun run docs:capability-status",
    );
    process.exit(1);
  }

  if (stable(current) !== stable(generated)) {
    console.error("✗ capability-status: drift detected; run bun run docs:capability-status");
    process.exit(1);
  }
  console.log("✓ capability-status: in sync");
}

main();
