/**
 * Generate reference partials under `docs/_generated/` from source-of-truth
 * code, replacing hand-authored reference content in pages tagged
 * `diataxis: reference`.
 *
 * Usage:
 *   bun scripts/docs-reference.ts --write   # regenerate all partials
 *   bun scripts/docs-reference.ts --check   # fail on drift (no writes)
 *
 * Each partial under `docs/_generated/` follows the schema documented in
 * `docs/_generated/README.md`:
 *   <!-- AUTO-GENERATED by scripts/docs-reference.ts — do not edit -->
 *   <!-- Source of truth: <space-separated paths> (<extraction method>) -->
 *   <!-- Generated at: <UTC ISO 8601, second precision> -->
 *   <!-- Generator commit: <git short SHA at run time> -->
 *
 *   <body>
 *
 * The drift gate (`docs:reference:check`, run from `bun run check`) excludes
 * the timestamp line from comparison; everything else (sources, commit SHA,
 * body) participates in the diff.
 */

import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { getHostSurfaceExports } from "./lib/package-introspection.ts";

const ROOT = resolve(import.meta.dirname, "..");
const GENERATED_DIR = join(ROOT, "docs/_generated");

// SOURCE-OF-TRUTH-DEBT: the per-package `intro` strings here are editorial
// (they describe the bullet list in human language). Symbol lists are fully
// source-derived from `@hostSurface` JSDoc tags; only these intro lines are
// hand-authored. A future port should either move them into JSDoc on the
// package's `index.ts` module-level comment or into the package manifest's
// `agentsJs.docsHostSurfaceIntro` field. Tracked alongside Port 2.
const STABLE_SURFACE_PACKAGES = [
  {
    pkg: "@agents-js/acp",
    srcDir: "packages/acp/src",
    intro: "The supported `@agents-js/acp` host-facing exports are:",
  },
  {
    pkg: "@agents-js/acp-host",
    srcDir: "packages/acp-host/src",
    intro: "The supported `@agents-js/acp-host` orchestration surface is centered on:",
  },
] as const;

interface PartialSpec {
  name: string;
  sources: string[];
  /** Description of how the body is derived; appears in the source-of-truth header. */
  extractionMethod: string;
  body: () => string;
}

const PARTIALS: PartialSpec[] = [
  {
    name: "acp-host-stable-surface.md",
    sources: STABLE_SURFACE_PACKAGES.map((p) => p.srcDir),
    extractionMethod: "@hostSurface JSDoc tags via ts-morph",
    body() {
      const sections: string[] = [];
      for (const { srcDir, intro } of STABLE_SURFACE_PACKAGES) {
        const names = getHostSurfaceExports(join(ROOT, srcDir));
        if (names.length === 0) {
          throw new Error(
            `No @hostSurface exports found under ${srcDir}. Either tag at least one declaration or remove the package from STABLE_SURFACE_PACKAGES in scripts/docs-reference.ts.`,
          );
        }
        const lines = [intro, "", ...names.map((n) => `- \`${n}\``)];
        sections.push(lines.join("\n"));
      }
      return sections.join("\n\n");
    },
  },
];

const TIMESTAMP_LINE_RE = /^<!-- Generated at: [^\n]*-->\n?/m;

/**
 * Drift normalization (Adjustment 3 of the docs governance plan):
 *   1. Strip trailing whitespace on every line.
 *   2. Collapse runs of trailing blank lines to a single final \n.
 *   3. Drop the `<!-- Generated at: ... -->` line entirely.
 * Used by `--check` to compare on-disk partials with regenerated bytes
 * without spurious-failing on timestamp churn.
 */
export function normalizeForDriftCheck(content: string): string {
  const withoutTimestamp = content.replace(TIMESTAMP_LINE_RE, "");
  const noTrailingWs = withoutTimestamp
    .split("\n")
    .map((line) => line.replace(/[ \t]+$/, ""))
    .join("\n");
  return noTrailingWs.replace(/\n+$/, "\n");
}

function gitShortSha(): string {
  // Use spawnSync with an explicit argv array so no shell is involved; the
  // command and its args are fully static, but the safer-by-default path
  // makes the surrounding generator harder to misuse if extended later.
  const result = spawnSync("git", ["rev-parse", "--short", "HEAD"], {
    cwd: ROOT,
    encoding: "utf-8",
  });
  if (result.status !== 0 || !result.stdout) {
    // Generator runs from a fresh clone or detached worktree without git
    // history are valid; surface a stable placeholder rather than failing.
    return "no-git";
  }
  return result.stdout.trim();
}

function nowUtc(): string {
  // Second precision is enough for human readability; sub-second precision
  // would just churn the line on every run without aiding any consumer.
  return new Date().toISOString().replace(/\.\d{3}Z$/, "Z");
}

function buildPartial(spec: PartialSpec): string {
  const lines = [
    "<!-- AUTO-GENERATED by scripts/docs-reference.ts — do not edit -->",
    `<!-- Source of truth: ${spec.sources.join(" ")} (${spec.extractionMethod}) -->`,
    `<!-- Generated at: ${nowUtc()} -->`,
    `<!-- Generator commit: ${gitShortSha()} -->`,
    "",
    spec.body(),
    "",
  ];
  return lines.join("\n");
}

function ensureGeneratedDir(): void {
  if (!existsSync(GENERATED_DIR)) {
    mkdirSync(GENERATED_DIR, { recursive: true });
  }
}

function main(): void {
  const checkMode = process.argv.includes("--check");
  const writeMode = process.argv.includes("--write");

  if (checkMode === writeMode) {
    console.error("Usage: bun scripts/docs-reference.ts (--check | --write)");
    process.exit(2);
  }

  ensureGeneratedDir();

  let drift = 0;
  for (const spec of PARTIALS) {
    const filePath = join(GENERATED_DIR, spec.name);
    const generated = buildPartial(spec);
    if (writeMode) {
      writeFileSync(filePath, generated, "utf-8");
      console.log(`✅ wrote docs/_generated/${spec.name}`);
      continue;
    }
    const current = existsSync(filePath) ? readFileSync(filePath, "utf-8") : "";
    if (normalizeForDriftCheck(current) !== normalizeForDriftCheck(generated)) {
      console.error(`✗ docs/_generated/${spec.name}: drift detected; run bun run docs:reference`);
      drift++;
    } else {
      console.log(`✓ docs/_generated/${spec.name}: in sync`);
    }
  }

  if (checkMode && drift > 0) {
    console.error(`\n${drift} partial(s) drifted from source.`);
    process.exit(1);
  }
}

if (import.meta.main) {
  main();
}
