/**
 * Generate reference partials under `docs/_generated/` from source-of-truth
 * code, replacing hand-authored reference content in pages tagged
 * `diataxis: reference`.
 *
 * Usage:
 *   bun scripts/docs-reference.ts --write   # regenerate all partials
 *   bun scripts/docs-reference.ts --check   # fail on drift (no writes)
 *
 * Each partial under `docs/_generated/` follows the schema documented in
 * `docs/_generated/README.md`:
 *   <!-- AUTO-GENERATED by scripts/docs-reference.ts — do not edit -->
 *   <!-- Source of truth: <space-separated paths> (<extraction method>) -->
 *   <!-- Generated at: <UTC ISO 8601, second precision> -->
 *   <!-- Generator commit: <git short SHA at run time> -->
 *
 *   <body>
 *
 * The drift gate (`docs:reference:check`, run from `bun run check`) excludes
 * the timestamp line from comparison; everything else (sources, commit SHA,
 * body) participates in the diff.
 */

import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import {
  getCLISubcommandFlags,
  getDiscriminatedUnionVariants,
  getFlatValidationSchemaExports,
  getHostLifecycleMethods,
  getHostObservabilityExports,
  getHostProcessFunctions,
  getHostSurfaceExports,
  getInterfaceFieldSignatures,
  getIntersectionUnionDiscriminants,
  getMethodKeyedRegistryEntries,
  getRuntimeRegistryMatrix,
} from "./lib/package-introspection.ts";

const ROOT = resolve(import.meta.dirname, "..");
const GENERATED_DIR = join(ROOT, "docs/_generated");

// SOURCE-OF-TRUTH-DEBT: the per-partial `intro` strings here are editorial
// (they describe the bullet list in human language). Symbol lists are fully
// source-derived from JSDoc tags; only these intro lines are hand-authored.
// A future port should either move them into JSDoc on the package's
// `index.ts` module-level comment or into the package manifest under
// `agentsJs.docs*Intro` fields. The same debt applies to the lifecycle,
// process-creation, and (future Port 3) observability/canonical-events
// intros below.
const STABLE_SURFACE_PACKAGES = [
  {
    pkg: "@agents-js/acp",
    srcDir: "packages/acp/src",
    intro: "The supported `@agents-js/acp` host-facing exports are:",
  },
  {
    pkg: "@agents-js/acp-host",
    srcDir: "packages/acp-host/src",
    intro: "The supported `@agents-js/acp-host` orchestration surface is centered on:",
  },
] as const;

interface PartialSpec {
  name: string;
  sources: string[];
  /** Description of how the body is derived; appears in the source-of-truth header. */
  extractionMethod: string;
  body: () => string;
}

const PARTIALS: PartialSpec[] = [
  {
    name: "acp-host-stable-surface.md",
    sources: STABLE_SURFACE_PACKAGES.map((p) => p.srcDir),
    extractionMethod: "@hostSurface JSDoc tags via ts-morph",
    body() {
      const sections: string[] = [];
      for (const { srcDir, intro } of STABLE_SURFACE_PACKAGES) {
        const names = getHostSurfaceExports(join(ROOT, srcDir));
        if (names.length === 0) {
          throw new Error(
            `No @hostSurface exports found under ${srcDir}. Either tag at least one declaration or remove the package from STABLE_SURFACE_PACKAGES in scripts/docs-reference.ts.`,
          );
        }
        const lines = [intro, "", ...names.map((n) => `- \`${n}\``)];
        sections.push(lines.join("\n"));
      }
      return sections.join("\n\n");
    },
  },
  {
    name: "acp-controller-lifecycle.md",
    sources: ["packages/acp/src"],
    extractionMethod: "@hostLifecycle JSDoc tags via ts-morph",
    body() {
      const methods = getHostLifecycleMethods(join(ROOT, "packages/acp/src"));
      if (methods.length === 0) {
        throw new Error(
          "No @hostLifecycle methods found under packages/acp/src. Either tag at least one method on ACPClientController or remove this entry from PARTIALS in scripts/docs-reference.ts.",
        );
      }
      const lines = [
        "The supported `ACPClientController` lifecycle methods are:",
        "",
        ...methods.map((n) => `- \`${n}\``),
      ];
      return lines.join("\n");
    },
  },
  {
    name: "acp-process-creation.md",
    sources: ["packages/acp/src", "packages/acp-host/src"],
    extractionMethod: "@hostProcess JSDoc tags via ts-morph",
    body() {
      const acpFns = getHostProcessFunctions(join(ROOT, "packages/acp/src"));
      const hostFns = getHostProcessFunctions(join(ROOT, "packages/acp-host/src"));
      const all = [...acpFns, ...hostFns].sort((a, b) => a.localeCompare(b));
      if (all.length === 0) {
        throw new Error(
          "No @hostProcess functions found across packages/acp/src or packages/acp-host/src. Either tag at least one function or remove this entry from PARTIALS.",
        );
      }
      const lines = [
        "The supported host-managed process-creation entry points are:",
        "",
        ...all.map((n) => `- \`${n}\``),
      ];
      return lines.join("\n");
    },
  },
  {
    name: "acp-canonical-events.md",
    sources: ["packages/acp-host/src/types/session.ts"],
    extractionMethod: "ACPSessionEvent discriminated-union variants via ts-morph",
    body() {
      const variants = getDiscriminatedUnionVariants(
        join(ROOT, "packages/acp-host/src"),
        "ACPSessionEvent",
        "type",
      );
      if (variants.length === 0) {
        throw new Error(
          "ACPSessionEvent has no variants. Either restore at least one or defer this extraction in _generated/README.md Deferred extractions.",
        );
      }
      const lines = [
        "The canonical `ACPSessionEvent` variants are:",
        "",
        ...variants.map((v) => `- \`${v}\``),
      ];
      return lines.join("\n");
    },
  },
  {
    name: "acp-session-hooks.md",
    sources: ["packages/acp-host/src/types/hooks.ts"],
    extractionMethod: "SessionHooks interface fields via ts-morph (source order)",
    body() {
      const fields = getInterfaceFieldSignatures(
        join(ROOT, "packages/acp-host/src"),
        "SessionHooks",
      );
      if (fields.length === 0) {
        throw new Error(
          "SessionHooks has no members. Either restore the interface or defer this extraction.",
        );
      }
      const lines = ["The `SessionHooks` interface members are:", ""];
      for (const f of fields) {
        const opt = f.optional ? "?" : "";
        lines.push(`- \`${f.name}${opt}: ${f.signature}\``);
      }
      return lines.join("\n");
    },
  },
  {
    name: "acp-session-mapping.md",
    sources: ["packages/acp/src/host-surface-sdk.ts"],
    extractionMethod:
      "SessionUpdate intersection-union discriminants via ts-morph (re-export resolution from @agentclientprotocol/sdk)",
    body() {
      const variants = getIntersectionUnionDiscriminants(
        join(ROOT, "packages/acp/src"),
        "SessionUpdate",
        "sessionUpdate",
      );
      if (variants.length === 0) {
        throw new Error(
          "SessionUpdate has no variants. Either restore the SDK re-export or defer this extraction.",
        );
      }
      const lines = [
        "The ACP `SessionUpdate` discriminant values that `ACPSessionController` translates to host events:",
        "",
        ...variants.map((v) => `- \`${v}\``),
      ];
      return lines.join("\n");
    },
  },
  {
    name: "acp-validated-surface.md",
    sources: ["packages/validation/src/acp.ts", "packages/validation/src/generated/acp-schema.ts"],
    extractionMethod:
      "@hostValidator-tagged Map<ACPMethod, ACPMethodSchemaInfo> registries via ts-morph",
    body() {
      const reqs = getMethodKeyedRegistryEntries(
        join(ROOT, "packages/validation/src"),
        "acpRequestSchemas",
      );
      const resps = getMethodKeyedRegistryEntries(
        join(ROOT, "packages/validation/src"),
        "acpResponseSchemas",
      );
      if (reqs.length === 0 || resps.length === 0) {
        throw new Error(
          "acpRequestSchemas / acpResponseSchemas resolved to an empty entry list. Either restore generated artifacts or defer this extraction in _generated/README.md Deferred extractions.",
        );
      }
      const lines = [
        "The validated ACP surface in `@agents-js/validation` covers these method/schema pairings.",
        "",
        "ACP request and notification methods:",
        "",
        ...reqs.map((e) => `- \`${e.method}\` → \`${e.schemaName}\``),
        "",
        "ACP response methods:",
        "",
        ...resps.map((e) => `- \`${e.method}\` → \`${e.schemaName}\``),
      ];
      return lines.join("\n");
    },
  },
  {
    name: "a2a-server-bridge.md",
    sources: ["packages/validation/src/a2a.ts"],
    extractionMethod: "@hostValidator-tagged a2aValidationSchemas object literal via ts-morph",
    body() {
      const entries = getFlatValidationSchemaExports(
        join(ROOT, "packages/validation/src"),
        "a2aValidationSchemas",
      );
      const lines = [
        "The server-side A2A bridge in `@agents-js/validation` registers these schemas:",
        "",
        ...entries.map((e) => `- \`${e.name}\` (${e.kind})`),
      ];
      return lines.join("\n");
    },
  },
  {
    name: "acp-observability-surface.md",
    sources: ["packages/acp-host/src"],
    extractionMethod: "@hostObservability JSDoc tags via ts-morph",
    body() {
      const names = getHostObservabilityExports(join(ROOT, "packages/acp-host/src"));
      if (names.length === 0) {
        throw new Error(
          "No @hostObservability exports found under packages/acp-host/src. Either tag at least one declaration or remove this entry from PARTIALS.",
        );
      }
      const lines = [
        "The `@agents-js/acp-host` observability surface is:",
        "",
        ...names.map((n) => `- \`${n}\``),
      ];
      return lines.join("\n");
    },
  },
  {
    name: "cli-command-table.md",
    sources: [
      "packages/cli/src/acp.ts",
      "packages/cli/src/bridge.ts",
      "packages/cli/src/serve.ts",
      "packages/cli/src/mcp.ts",
      "packages/cli/src/send.ts",
      "packages/cli/src/shared-arg-specs.ts",
    ],
    extractionMethod:
      "@hostCliSubcommand-tagged ArgSpec literals via ts-morph (factory spreads flattened)",
    body() {
      const subcommands = [
        { module: "acp", title: "`agents-js acp`" },
        { module: "bridge", title: "`agents-js bridge`" },
        { module: "serve", title: "`agents-js serve`" },
        { module: "mcp", title: "`agents-js mcp`" },
        { module: "send", title: "`agents-js send`" },
      ] as const;
      const sections: string[] = ["The supported CLI subcommands and their flags are:", ""];
      for (const { module, title } of subcommands) {
        const flags = getCLISubcommandFlags(join(ROOT, "packages/cli/src"), module);
        if (flags.length === 0) {
          throw new Error(
            `No @hostCliSubcommand flags resolved for ${module}. Either tag the ArgSpec or remove the entry from cli-command-table.md.`,
          );
        }
        sections.push(`#### ${title}`);
        sections.push("");
        sections.push("| Flag | Kind | Description |");
        sections.push("| --- | --- | --- |");
        for (const f of flags) {
          const flagCol =
            f.kind === "value" && f.valueExample
              ? `\`${f.flag} ${f.valueExample}\``
              : `\`${f.flag}\``;
          // Pipe + backtick escaping is unnecessary — the parser-side
          // descriptions are short prose without literal pipes; if a future
          // edit introduces one, it will surface in `bun run docs:build`'s
          // table-validation pass and force the partial to be re-examined.
          sections.push(`| ${flagCol} | ${f.kind} | ${f.description} |`);
        }
        sections.push("");
      }
      return sections.join("\n").replace(/\n+$/, "");
    },
  },
  {
    name: "runtime-matrix.md",
    sources: ["packages/gateway-runtime/src/runtimes-registry.ts"],
    extractionMethod:
      "GATEWAY_RUNTIME_REGISTRY ObjectLiteralExpression via ts-morph (createAcpHarness call args)",
    body() {
      const rows = getRuntimeRegistryMatrix(
        join(ROOT, "packages/gateway-runtime/src"),
        "GATEWAY_RUNTIME_REGISTRY",
      );
      if (rows.length === 0) {
        throw new Error(
          "GATEWAY_RUNTIME_REGISTRY has no entries. Either restore at least one or defer this extraction.",
        );
      }
      const lines = [
        "The curated ACP runtimes wired into the gateway are:",
        "",
        "| Id | Display Name | Command | Description |",
        "| --- | --- | --- | --- |",
      ];
      for (const r of rows) {
        const command = r.command ? `\`${r.command}\`` : "—";
        lines.push(`| \`${r.id}\` | ${r.displayName} | ${command} | ${r.description} |`);
      }
      return lines.join("\n");
    },
  },
  {
    name: "agent-registry-schema.md",
    sources: ["packages/a2a-client/src/registry.ts"],
    extractionMethod: "A2AAgentEntry + ACPAgentEntry interface fields via ts-morph (source order)",
    body() {
      const a2a = getInterfaceFieldSignatures(
        join(ROOT, "packages/a2a-client/src"),
        "A2AAgentEntry",
      );
      const acp = getInterfaceFieldSignatures(
        join(ROOT, "packages/a2a-client/src"),
        "ACPAgentEntry",
      );
      if (a2a.length === 0 || acp.length === 0) {
        throw new Error(
          "Agent registry entry interfaces (A2AAgentEntry / ACPAgentEntry) have no members. Either restore them or defer this extraction.",
        );
      }
      const renderField = (f: { name: string; signature: string; optional: boolean }) =>
        `- \`${f.name}${f.optional ? "?" : ""}: ${f.signature}\``;
      const lines = [
        "Agent registry entries are a discriminated union on `kind`:",
        "",
        "**`A2AAgentEntry`** — remote A2A agents reachable over HTTP:",
        "",
        ...a2a.map(renderField),
        "",
        "**`ACPAgentEntry`** — locally spawnable ACP harnesses:",
        "",
        ...acp.map(renderField),
      ];
      return lines.join("\n");
    },
  },
];

const TIMESTAMP_LINE_RE = /^<!-- Generated at: [^\n]*-->\n?/m;
const COMMIT_LINE_RE = /^<!-- Generator commit: [^\n]*-->\n?/m;

/**
 * Drift normalization (Adjustment 3 of the docs governance plan, revised):
 *   1. Strip trailing whitespace on every line.
 *   2. Collapse runs of trailing blank lines to a single final \n.
 *   3. Drop the `<!-- Generated at: ... -->` line entirely.
 *   4. Drop the `<!-- Generator commit: ... -->` line entirely.
 *
 * Both lines are recorded for audit but excluded from drift comparison.
 * Including the commit SHA in drift was self-defeating: committing the
 * regenerated partial necessarily changes HEAD, so any committed-clean
 * state would immediately fail `docs:reference:check` on the very next
 * `bun run check`. The body diff already catches "source changed but
 * nobody regenerated" — which is the actual property the gate is for.
 */
export function normalizeForDriftCheck(content: string): string {
  const withoutVolatile = content.replace(TIMESTAMP_LINE_RE, "").replace(COMMIT_LINE_RE, "");
  const noTrailingWs = withoutVolatile
    .split("\n")
    .map((line) => line.replace(/[ \t]+$/, ""))
    .join("\n");
  return noTrailingWs.replace(/\n+$/, "\n");
}

function gitShortSha(): string {
  // Use spawnSync with an explicit argv array so no shell is involved; the
  // command and its args are fully static, but the safer-by-default path
  // makes the surrounding generator harder to misuse if extended later.
  const result = spawnSync("git", ["rev-parse", "--short", "HEAD"], {
    cwd: ROOT,
    encoding: "utf-8",
  });
  if (result.status !== 0 || !result.stdout) {
    // Generator runs from a fresh clone or detached worktree without git
    // history are valid; surface a stable placeholder rather than failing.
    return "no-git";
  }
  return result.stdout.trim();
}

function nowUtc(): string {
  // Second precision is enough for human readability; sub-second precision
  // would just churn the line on every run without aiding any consumer.
  return new Date().toISOString().replace(/\.\d{3}Z$/, "Z");
}

function buildPartial(spec: PartialSpec): string {
  const lines = [
    "<!-- AUTO-GENERATED by scripts/docs-reference.ts — do not edit -->",
    `<!-- Source of truth: ${spec.sources.join(" ")} (${spec.extractionMethod}) -->`,
    `<!-- Generated at: ${nowUtc()} -->`,
    `<!-- Generator commit: ${gitShortSha()} -->`,
    "",
    spec.body(),
    "",
  ];
  return lines.join("\n");
}

function ensureGeneratedDir(): void {
  if (!existsSync(GENERATED_DIR)) {
    mkdirSync(GENERATED_DIR, { recursive: true });
  }
}

function main(): void {
  const checkMode = process.argv.includes("--check");
  const writeMode = process.argv.includes("--write");

  if (checkMode === writeMode) {
    console.error("Usage: bun scripts/docs-reference.ts (--check | --write)");
    process.exit(2);
  }

  ensureGeneratedDir();

  let drift = 0;
  for (const spec of PARTIALS) {
    const filePath = join(GENERATED_DIR, spec.name);
    const generated = buildPartial(spec);
    if (writeMode) {
      writeFileSync(filePath, generated, "utf-8");
      console.log(`✅ wrote docs/_generated/${spec.name}`);
      continue;
    }
    const current = existsSync(filePath) ? readFileSync(filePath, "utf-8") : "";
    if (normalizeForDriftCheck(current) !== normalizeForDriftCheck(generated)) {
      console.error(`✗ docs/_generated/${spec.name}: drift detected; run bun run docs:reference`);
      drift++;
    } else {
      console.log(`✓ docs/_generated/${spec.name}: in sync`);
    }
  }

  if (checkMode && drift > 0) {
    console.error(`\n${drift} partial(s) drifted from source.`);
    process.exit(1);
  }
}

if (import.meta.main) {
  main();
}
