/**
 * Generate reference partials under `docs/_generated/` from source-of-truth
 * code, replacing hand-authored reference content in pages tagged
 * `diataxis: reference`.
 *
 * Usage:
 *   bun scripts/docs-reference.ts --write   # regenerate all partials
 *   bun scripts/docs-reference.ts --check   # fail on drift (no writes)
 *
 * Each partial under `docs/_generated/` follows the schema documented in
 * `docs/_generated/README.md`:
 *   <!-- AUTO-GENERATED by scripts/docs-reference.ts — do not edit -->
 *   <!-- Source of truth: <space-separated paths> (<extraction method>) -->
 *   <!-- Generated at: <UTC ISO 8601, second precision> -->
 *   <!-- Generator commit: <git short SHA at run time> -->
 *
 *   <body>
 *
 * The drift gate (`docs:reference:check`, run from `bun run check`) excludes
 * the timestamp line from comparison; everything else (sources, commit SHA,
 * body) participates in the diff.
 */

import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import {
  getCLISubcommandFlags,
  getMethodKeyedRegistryEntries,
  getRuntimeRegistryMatrix,
} from "./lib/package-introspection.ts";

const ROOT = resolve(import.meta.dirname, "..");
const GENERATED_DIR = join(ROOT, "docs/_generated");

interface PartialSpec {
  name: string;
  sources: string[];
  /** Description of how the body is derived; appears in the source-of-truth header. */
  extractionMethod: string;
  body: () => string;
}

/**
 * Escape a single Markdown table-cell value per GitHub-flavored Markdown
 * rules: `|` is the column separator, `\` is the escape lead-in, and a
 * literal newline ends the row. We replace each with the standard
 * GFM-tolerated alternatives so a description containing
 * `debug|info|warn|error|silent` (a real choice list in CLI flag prose)
 * renders as a single cell.
 */
function escapeMdTableCell(raw: string): string {
  return raw.replace(/\\/g, "\\\\").replace(/\|/g, "\\|").replace(/\r?\n/g, " ").trim();
}

const CLI_SUBCOMMAND_SECTIONS = [
  { argSpec: "ACP_ARG_SPEC", module: "acp", title: "`agents-js acp`" },
  { argSpec: "BRIDGE_ARG_SPEC", module: "bridge", title: "`agents-js bridge`" },
  { argSpec: "SERVE_ARG_SPEC", module: "serve", title: "`agents-js serve`" },
  { argSpec: "MCP_ROOT_ARG_SPEC", module: "mcp", title: "`agents-js mcp`" },
  { argSpec: "MCP_SETUP_ARG_SPEC", module: "mcp", title: "`agents-js mcp setup`" },
  { argSpec: "MCP_BRIDGE_ARG_SPEC", module: "mcp", title: "`agents-js mcp bridge`" },
  { argSpec: "SEND_ARG_SPEC", module: "send", title: "`agents-js send`" },
  {
    argSpec: "GENERATE_CONFIG_ARG_SPEC",
    module: "generate-config",
    title: "`agents-js generate-config`",
  },
] as const;

const PARTIALS: PartialSpec[] = [
  {
    name: "acp-validated-surface.md",
    sources: ["packages/validation/src/acp.ts", "packages/validation/src/generated/acp-schema.ts"],
    extractionMethod:
      "Map<ACPMethod, ACPMethodSchemaInfo> registries via ts-morph (looked up by exported variable name)",
    body() {
      const reqs = getMethodKeyedRegistryEntries(
        join(ROOT, "packages/validation/src"),
        "acpRequestSchemas",
      );
      const resps = getMethodKeyedRegistryEntries(
        join(ROOT, "packages/validation/src"),
        "acpResponseSchemas",
      );
      if (reqs.length === 0 || resps.length === 0) {
        throw new Error(
          "acpRequestSchemas / acpResponseSchemas resolved to an empty entry list. Restore generated artifacts or remove this partial.",
        );
      }
      const lines = [
        "The validated ACP surface in `@agents-js/validation` covers these method/schema pairings.",
        "",
        "ACP request and notification methods:",
        "",
        ...reqs.map((e) => `- \`${e.method}\` → \`${e.schemaName}\``),
        "",
        "ACP response methods:",
        "",
        ...resps.map((e) => `- \`${e.method}\` → \`${e.schemaName}\``),
      ];
      return lines.join("\n");
    },
  },
  {
    name: "cli-command-table.md",
    sources: [
      "packages/cli/src/acp.ts",
      "packages/cli/src/bridge.ts",
      "packages/cli/src/serve.ts",
      "packages/cli/src/mcp.ts",
      "packages/cli/src/send.ts",
      "packages/cli/src/shared-arg-specs.ts",
    ],
    extractionMethod:
      "ArgSpec literals via ts-morph, looked up by exported variable name (factory spreads flattened)",
    body() {
      const sections: string[] = ["The supported CLI subcommands and their flags are:", ""];
      for (const { argSpec, module, title } of CLI_SUBCOMMAND_SECTIONS) {
        const flags = getCLISubcommandFlags(join(ROOT, "packages/cli/src"), module, argSpec);
        if (flags.length === 0) {
          throw new Error(
            `No flags resolved for ${argSpec} in packages/cli/src/${module}.ts. Restore the literal or remove the entry from CLI_SUBCOMMAND_SECTIONS.`,
          );
        }
        sections.push(`#### ${title}`);
        sections.push("");
        sections.push("| Flag | Kind | Description |");
        sections.push("| --- | --- | --- |");
        for (const f of flags) {
          const flagCol =
            f.kind === "value" && f.valueExample
              ? `\`${f.flag} ${f.valueExample}\``
              : `\`${f.flag}\``;
          sections.push(`| ${flagCol} | ${f.kind} | ${escapeMdTableCell(f.description)} |`);
        }
        sections.push("");
      }
      return sections.join("\n").replace(/\n+$/, "");
    },
  },
  {
    name: "runtime-matrix.md",
    sources: ["packages/gateway-runtime/src/runtimes-registry.ts"],
    extractionMethod:
      "GATEWAY_RUNTIME_REGISTRY ObjectLiteralExpression via ts-morph (createAcpHarness call args)",
    body() {
      const rows = getRuntimeRegistryMatrix(
        join(ROOT, "packages/gateway-runtime/src"),
        "GATEWAY_RUNTIME_REGISTRY",
      );
      if (rows.length === 0) {
        throw new Error(
          "GATEWAY_RUNTIME_REGISTRY has no entries. Restore at least one or remove this partial.",
        );
      }
      const lines = [
        "The curated ACP runtimes wired into the gateway are:",
        "",
        "| Id | Display Name | Command | Description |",
        "| --- | --- | --- | --- |",
      ];
      for (const r of rows) {
        const command = r.command ? `\`${r.command}\`` : "—";
        lines.push(
          `| \`${r.id}\` | ${escapeMdTableCell(r.displayName)} | ${command} | ${escapeMdTableCell(r.description)} |`,
        );
      }
      return lines.join("\n");
    },
  },
];

const TIMESTAMP_LINE_RE = /^<!-- Generated at: [^\n]*-->\n?/m;
const COMMIT_LINE_RE = /^<!-- Generator commit: [^\n]*-->\n?/m;

/**
 * Drift normalization (Adjustment 3 of the docs governance plan, revised):
 *   1. Strip trailing whitespace on every line.
 *   2. Collapse runs of trailing blank lines to a single final \n.
 *   3. Drop the `<!-- Generated at: ... -->` line entirely.
 *   4. Drop the `<!-- Generator commit: ... -->` line entirely.
 *
 * Both lines are recorded for audit but excluded from drift comparison.
 * Including the commit SHA in drift was self-defeating: committing the
 * regenerated partial necessarily changes HEAD, so any committed-clean
 * state would immediately fail `docs:reference:check` on the very next
 * `bun run check`. The body diff already catches "source changed but
 * nobody regenerated" — which is the actual property the gate is for.
 */
export function normalizeForDriftCheck(content: string): string {
  const withoutVolatile = content.replace(TIMESTAMP_LINE_RE, "").replace(COMMIT_LINE_RE, "");
  const noTrailingWs = withoutVolatile
    .split("\n")
    .map((line) => line.replace(/[ \t]+$/, ""))
    .join("\n");
  return noTrailingWs.replace(/\n+$/, "\n");
}

function gitShortSha(): string {
  // Use spawnSync with an explicit argv array so no shell is involved; the
  // command and its args are fully static, but the safer-by-default path
  // makes the surrounding generator harder to misuse if extended later.
  const result = spawnSync("git", ["rev-parse", "--short", "HEAD"], {
    cwd: ROOT,
    encoding: "utf-8",
  });
  if (result.status !== 0 || !result.stdout) {
    // Generator runs from a fresh clone or detached worktree without git
    // history are valid; surface a stable placeholder rather than failing.
    return "no-git";
  }
  return result.stdout.trim();
}

function nowUtc(): string {
  // Second precision is enough for human readability; sub-second precision
  // would just churn the line on every run without aiding any consumer.
  return new Date().toISOString().replace(/\.\d{3}Z$/, "Z");
}

function buildPartial(spec: PartialSpec): string {
  const lines = [
    "<!-- AUTO-GENERATED by scripts/docs-reference.ts — do not edit -->",
    `<!-- Source of truth: ${spec.sources.join(" ")} (${spec.extractionMethod}) -->`,
    `<!-- Generated at: ${nowUtc()} -->`,
    `<!-- Generator commit: ${gitShortSha()} -->`,
    "",
    spec.body(),
    "",
  ];
  return lines.join("\n");
}

function ensureGeneratedDir(): void {
  if (!existsSync(GENERATED_DIR)) {
    mkdirSync(GENERATED_DIR, { recursive: true });
  }
}

function main(): void {
  const checkMode = process.argv.includes("--check");
  const writeMode = process.argv.includes("--write");

  if (checkMode === writeMode) {
    console.error("Usage: bun scripts/docs-reference.ts (--check | --write)");
    process.exit(2);
  }

  ensureGeneratedDir();

  let drift = 0;
  for (const spec of PARTIALS) {
    const filePath = join(GENERATED_DIR, spec.name);
    const generated = buildPartial(spec);
    if (writeMode) {
      const current = existsSync(filePath) ? readFileSync(filePath, "utf-8") : "";
      if (current && normalizeForDriftCheck(current) === normalizeForDriftCheck(generated)) {
        console.log(`✓ docs/_generated/${spec.name}: current`);
        continue;
      }
      writeFileSync(filePath, generated, "utf-8");
      console.log(`✅ wrote docs/_generated/${spec.name}`);
      continue;
    }
    const current = existsSync(filePath) ? readFileSync(filePath, "utf-8") : "";
    if (normalizeForDriftCheck(current) !== normalizeForDriftCheck(generated)) {
      console.error(`✗ docs/_generated/${spec.name}: drift detected; run bun run docs:reference`);
      drift++;
    } else {
      console.log(`✓ docs/_generated/${spec.name}: in sync`);
    }
  }

  if (checkMode && drift > 0) {
    console.error(`\n${drift} partial(s) drifted from source.`);
    process.exit(1);
  }
}

if (import.meta.main) {
  main();
}
