#!/usr/bin/env bun
/**
 * Run `bun test` per workspace package and write a snapshot of pass/fail/file
 * counts to output/test-counts.json. Reads the package list from
 * docs/public/graph.json (generated by scripts/dep-graph-gen.ts).
 *
 * Skips packages that don't define a `test` script in their package.json.
 * Packages whose tests fail are recorded with their failure summary; this
 * script does not exit non-zero on test failures because the dashboard wants
 * to show "N failing" rather than abort.
 */

import { spawn } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "..");
const GRAPH = resolve(REPO_ROOT, "docs/public/graph.json");
const OUT = resolve(REPO_ROOT, "output/test-counts.json");

interface GraphPkg {
  name: string;
  dir: string;
  private: boolean;
}

interface CountResult {
  pass: number | null;
  fail: number | null;
  files: number | null;
  exitCode: number;
  /** Whether the package has a `test` script in package.json. */
  hasTestScript: boolean;
  /** Captured "N pass / N fail / Ran N tests" trailing summary, if matched. */
  summary: string | null;
}

const SUMMARY_RE =
  /(\d+)\s+pass[\s\S]*?(\d+)\s+fail[\s\S]*?Ran\s+\d+\s+tests\s+across\s+(\d+)\s+files?/;

function readPackageJson(dir: string): Record<string, unknown> {
  return JSON.parse(readFileSync(join(REPO_ROOT, dir, "package.json"), "utf8"));
}

async function runTests(cwd: string): Promise<{ output: string; exitCode: number }> {
  return new Promise((resolveFn) => {
    let output = "";
    const child = spawn("bun", ["test"], { cwd, env: { ...process.env, NO_COLOR: "1" } });
    child.stdout.on("data", (chunk: Buffer) => {
      output += chunk.toString();
    });
    child.stderr.on("data", (chunk: Buffer) => {
      output += chunk.toString();
    });
    child.on("close", (code) => resolveFn({ output, exitCode: code ?? -1 }));
  });
}

async function main() {
  const graph = JSON.parse(readFileSync(GRAPH, "utf8")) as { packages: GraphPkg[] };
  const results: Record<string, CountResult> = {};

  for (const pkg of graph.packages) {
    // Apps aren't on the dashboard's package list; skip them. The dashboard
    // covers packages/, extras/, and tests/trial-agent.
    if (pkg.dir.startsWith("apps/")) continue;

    let manifest: Record<string, unknown>;
    try {
      manifest = readPackageJson(pkg.dir);
    } catch {
      continue;
    }
    const scripts = (manifest.scripts as Record<string, string> | undefined) ?? {};
    const hasTestScript = typeof scripts.test === "string";

    if (!hasTestScript) {
      results[pkg.name] = {
        pass: null,
        fail: null,
        files: null,
        exitCode: 0,
        hasTestScript: false,
        summary: null,
      };
      continue;
    }

    process.stdout.write(`[test-counts] ${pkg.name} … `);
    const { output, exitCode } = await runTests(join(REPO_ROOT, pkg.dir));
    const match = output.match(SUMMARY_RE);
    const result: CountResult = match
      ? {
          pass: Number.parseInt(match[1] ?? "0", 10),
          fail: Number.parseInt(match[2] ?? "0", 10),
          files: Number.parseInt(match[3] ?? "0", 10),
          exitCode,
          hasTestScript: true,
          summary: `${match[1]} pass / ${match[2]} fail / ${match[3]} files`,
        }
      : { pass: null, fail: null, files: null, exitCode, hasTestScript: true, summary: null };

    process.stdout.write(`${result.summary ?? `(no summary, exit=${exitCode})`}\n`);
    results[pkg.name] = result;
  }

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(
    OUT,
    `${JSON.stringify({ generated_at: new Date().toISOString(), packages: results }, null, 2)}\n`,
  );
  process.stdout.write(`\n[test-counts] wrote ${OUT}\n`);
}

await main();
