export type {
  AuthenticateRequest,
  AuthenticateResponse,
  AuthMethod,
  ClientCapabilities,
  CloseSessionRequest,
  CloseSessionResponse,
  CompleteElicitationNotification,
  CreateElicitationRequest,
  CreateElicitationResponse,
  ElicitationCapabilities,
  ForkSessionRequest,
  ForkSessionResponse,
  InitializeResponse,
  PromptResponse,
  ResumeSessionRequest,
  ResumeSessionResponse,
  Stream,
} from "@agentclientprotocol/sdk";
